// @djcastaldo 08-01-2025
// setup to access key index from outside keymap
#pragma once

//  <~>~<~>~<~>~<~>~<~>~<~>~<~>~<~>~<~>~<~>~<~>~<~>~<~>~<~>~<~>
//  ~=~=~=~=~=~=~=~=~=~=~=~ LED Indexes ~=~=~=~=~=~=~=~=~=~=~=~
//  Agar has underglow, but the only easily visible leds are only the caps lock leds at index 0
// useful key indexes
enum key_indexes {
    I_INDICATOR = 15,
    I_ESC = 0,
    I_BBRTEXT = 0,
    I_N1 = 0,
    I_N2 = 0,
    I_N3 = 0,
    I_N4 = 0,
    I_N5 = 0,
    I_N6 = 0,
    I_N7 = 0,
    I_N8 = 0,
    I_N9 = 0,
    I_N0 = 0,
    I_MIN = 0,
    I_PLUS = 0,
    I_BSLS = 0,
    I_NUMLOCK = 0,
    I_SLOCK = 0,
    I_GRV = 0,
    I_INS = 0,
    I_LLOCK = 15,
    I_TAB = 0,
    I_Q = 0,
    I_W = 0,
    I_E = 0,
    I_R = 0,
    I_T = 0,
    I_Y = 0,
    I_U = 0,
    I_I = 0,
    I_O = 0,
    I_P = 0,
    I_MREC1 = 0,
    I_MREC2 = 0,
    I_PGUP = 0,
    I_HOME = 0,
    I_BARTEXT = 0,
    I_CAPS = 0,
    I_FN = 0,
    I_A = 0,
    I_S = 0,
    I_D = 0,
    I_F = 0,
    I_G = 0,
    I_H = 0,
    I_J = 0,
    I_K = 0,
    I_KLOCK = 15,
    I_L = 0,
    I_LEAD = 0,
    I_SEMI = 0,
    I_KTRACK = 0,
    I_APOS = 0,
    I_FJLIGHT = 0,
    I_HROWLIGHT = 0,
    I_ENT = 0,
    I_PGDN = 0,
    I_END = 0,
    I_UNDERLN = 0,
    I_MHLD = 0,
    I_SSHOT = 0,
    I_LSFT = 0,
    I_Z = 0,
    I_X = 0,
    I_C = 0,
    I_V = 0,
    I_B = 0,
    I_N = 0,
    I_M = 0,
    I_COMMA = 0,
    I_MPLY1 = 0,
    I_DOT = 0,
    I_MPLY2 = 0,
    I_RSFT = 0,
    I_UP = 0,
    I_FKEY = 0,
    I_STHRU = 0,
    I_LCTL = 0,
    I_LGUI = 0,
    I_LOPT = 0,
    I_LALT = 0,
    I_LCMD = 0,
    I_SPACE = 0,
    I_RALT = 0,
    I_RCMD = 0,
    I_RCTL = 0,
    I_LEFT = 0,
    I_DOWN = 0,
    I_RIGHT = 0
};

// for sending index to color array after a config.h define
typedef struct {
    uint8_t index;
    uint8_t r;
    uint8_t g;
    uint8_t b;
} led_color_t;
